const {
    handlePm2, handleDocker, handleDockerImages, handleDockerStats,
    handleDf, handleFree, handleUptime, handleWho, handleTop,
    handleSs, handleIp, handleToolsList
} = require('./handler');

module.exports = {
    name: 'tools',
    commands: [
        {
            name: 'pm2',
            aliases: ['pm2status'],
            description: 'PM2 process list',
            usage: 'pm2',
            module: 'tools',
            permission: 'admin',
            handler: handlePm2,
        },
        {
            name: 'docker',
            aliases: ['dockerps'],
            description: 'Docker containers aktif',
            usage: 'docker',
            module: 'tools',
            permission: 'admin',
            handler: handleDocker,
        },
        {
            name: 'docker images',
            aliases: ['dimages'],
            description: 'Docker images',
            usage: 'docker images',
            module: 'tools',
            permission: 'admin',
            handler: handleDockerImages,
        },
        {
            name: 'docker stats',
            aliases: ['dstats'],
            description: 'Docker resource usage',
            usage: 'docker stats',
            module: 'tools',
            permission: 'admin',
            handler: handleDockerStats,
        },
        {
            name: 'df',
            aliases: ['disk'],
            description: 'Disk usage',
            usage: 'df',
            module: 'tools',
            permission: 'user',
            handler: handleDf,
        },
        {
            name: 'free',
            aliases: ['ram', 'memory'],
            description: 'Memory usage (free -h)',
            usage: 'free',
            module: 'tools',
            permission: 'user',
            handler: handleFree,
        },
        {
            name: 'uptime',
            aliases: [],
            description: 'Server uptime & load',
            usage: 'uptime',
            module: 'tools',
            permission: 'user',
            handler: handleUptime,
        },
        {
            name: 'who',
            aliases: ['users-online'],
            description: 'User yang sedang login',
            usage: 'who',
            module: 'tools',
            permission: 'admin',
            handler: handleWho,
        },
        {
            name: 'top',
            aliases: ['procs'],
            description: 'Top proses (by CPU)',
            usage: 'top',
            module: 'tools',
            permission: 'admin',
            handler: handleTop,
        },
        {
            name: 'ports',
            aliases: ['ss', 'netstat'],
            description: 'Port yang terbuka',
            usage: 'ports',
            module: 'tools',
            permission: 'admin',
            handler: handleSs,
        },
        {
            name: 'ip',
            aliases: ['ipaddr'],
            description: 'IP address server',
            usage: 'ip',
            module: 'tools',
            permission: 'admin',
            handler: handleIp,
        },
        {
            name: 'tools',
            aliases: ['toolslist'],
            description: 'Daftar semua tools',
            usage: 'tools',
            module: 'tools',
            permission: 'user',
            handler: handleToolsList,
        },
    ],
};
